parameters:
    app.orbit_client.class: BBC\BrandingClient\OrbitStubClient
    app.branding_client.class: BBC\BrandingClient\BrandingStubClient
    app.metric_backend.class: App\Metrics\Backend\NullMetricBackend
    app.metric_cache.class: App\Metrics\Cache\MetricCacheNull
    app.ada.class_service.class: App\ExternalApi\Ada\Service\AdaClassStubService
    app.ada.programme_service.class: App\ExternalApi\Ada\Service\AdaProgrammeStubService
    app.electron.service.class: App\ExternalApi\Electron\Service\ElectronStubService
    app.idtquiz.service.class: App\ExternalApi\IdtQuiz\IdtQuizStubService
    app.morph.service.lxpromo.class: App\ExternalApi\Morph\Service\LxPromoStubService
    app.receng.service.class: App\ExternalApi\RecEng\Service\RecEngStubService
    app.recipe.service.class: App\ExternalApi\Recipes\Service\RecipesStubService
    app.favourites.service.class: App\ExternalApi\FavouritesButton\Service\FavouritesButtonStubService
    app.tupac.service.class: App\ExternalApi\Tupac\Service\TupacStubService
    app.isite.article_service.class: App\ExternalApi\Isite\Service\ArticleFakeService
    app.isite.profile_service.class: App\ExternalApi\Isite\Service\ProfileFakeService
    app.sounds_nav.service.class: App\ExternalApi\SoundsNav\Service\SoundsNavStubService

framework:
    cache:
        pools:
            cache.programmes:
                provider: cache.null_provider

services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

